version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python-socketio
    versions:
    - 5.0.4
    - 5.1.0
  - dependency-name: python-engineio
    versions:
    - 4.0.0
    - 4.0.1
  - dependency-name: soupsieve
    versions:
    - "2.1"
    - "2.2"
  - dependency-name: lxml
    versions:
    - 4.6.2
  - dependency-name: jinja2
    versions:
    - 2.11.2
  - dependency-name: pillow
    versions:
    - 6.2.1
